In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('data - data.csv')

In [4]:
df.head()

x          y
0  48.955889  60.723602
1  44.687196  82.892504
2  60.297327  97.379897
3  45.618644  48.847153
4  38.816818  56.877213

In [7]:
x = df['x']

In [8]:
x.head()

0    48.955889
1    44.687196
2    60.297327
3    45.618644
4    38.816818
Name: x, dtype: float64

In [9]:
y = df['y']

In [10]:
y.head()

0    60.723602
1    82.892504
2    97.379897
3    48.847153
4    56.877213
Name: y, dtype: float64

# Linear Regression using Gradient Decent

In [12]:
m =0
c = 0
l = 0.0001

iteration = 1000

n = int(len(x))

for i in range(iteration):
    pred = (m*x)+c
    der_m = (-2/n)*sum(x*(y-pred))
    der_c = (-2/n)*sum((y-pred))
    
    m = m - (l*der_m)
    c = c - (l*der_c)
    
print(m, c)

1.4796491688881985 0.10148121497503648


In [13]:
out = (m*44.687196)+c

In [14]:
out

66.22285363631907

In [15]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [16]:
lr.fit(df[['x']], df[['y']])

LinearRegression()

In [17]:
lr.predict([[44.687196]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[67.43699731]])

In [18]:
lr.coef_

array([[1.28735737]])

In [19]:
lr.intercept_

array([9.90860619])